name: Create Branch from Tag

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-branch:
    permissions:
      contents: write
    name: Create Branch from Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Branch
        id: create_branch
        uses: lablnet/create-branch-from-tag@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        